# server.py
from mcp.server.fastmcp import FastMCP

# Create an MCP server
mcp = FastMCP("Demo")

#
# Tools
#

# get-orders: 
# This tool will return a list of orders. The optional input is a customer ID, 
# and the output is a list of orders. Each order should contain the following fields:
# ID, customer ID, quantity, total price, and status.
@mcp.tool()
def get_orders(customer_id: int = None) -> list[dict]:
    """Retrieve a list of orders, optionally filtered by customer ID
    args:
        customer_id (int, optional): The ID of the customer to filter orders by. Defaults to None.
    returns:
        list[dict]: A list of orders, each represented as a dictionary with fields:
                    ID, customer ID, quantity, total price, and status.
    """
    # Sample data representing orders
    orders = [
        {"id": 1, "customer_id": 101, "quantity": 2, "total_price": 50.0, "status": "shipped"},
        {"id": 2, "customer_id": 102, "quantity": 1, "total_price": 20.0, "status": "processing"},
        {"id": 3, "customer_id": 101, "quantity": 3, "total_price": 75.0, "status": "delivered"},
    ]
    
    if customer_id is not None:
        # Filter orders by customer ID
        orders = [order for order in orders if order["customer_id"] == customer_id]
    
    return orders

# get-order:
# This tool will return a specific order. The input is the order ID, and the output is an order. 
# The order should contain the following fields: ID, customer ID, quantity, total price, and status.
@mcp.tool()
def get_order(order_id: int) -> dict:
    """Retrieve a specific order by its ID
    args:
        order_id (int): The ID of the order to retrieve.
    returns:
        dict: A dictionary representing the order with fields:
              ID, customer ID, quantity, total price, and status.
    """
    # Sample data representing orders
    orders = {
        1: {"id": 1, "customer_id": 101, "quantity": 2, "total_price": 50.0, "status": "shipped"},
        2: {"id": 2, "customer_id": 102, "quantity": 1, "total_price": 20.0, "status": "processing"},
        3: {"id": 3, "customer_id": 101, "quantity": 3, "total_price": 75.0, "status": "delivered"},
    }
    
    return orders.get(order_id, {})

# place-order: This tool will place an order. The input is the customer ID and the cart ID.
@mcp.tool()
def place_order(customer_id: int, cart_id: int) -> dict:
    """Place an order for a given customer and cart
    args:
        customer_id (int): The ID of the customer placing the order.
        cart_id (int): The ID of the cart to place the order from.
    returns:
        dict: A dictionary representing the placed order with fields:
              ID, customer ID, quantity, total price, and status.
    """
    # Simulate placing an order
    new_order = {
        "id": 4,  # In a real scenario, this would be generated by the database
        "customer_id": customer_id,
        "quantity": 5,  # This would be calculated based on the cart contents
        "total_price": 100.0,  # This would also be calculated based on the cart contents
        "status": "processing"
    }
    
    return new_order

# get-cart: 
# This tool will return a cart.
@mcp.tool()
def get_cart(cart_id: int) -> dict:
    """Retrieve a cart by its ID
    args:
        cart_id (int): The ID of the cart to retrieve.
    returns:
        dict: A dictionary representing the cart with fields:
              ID, customer ID, items, and total price.
    """
    # Sample data representing carts
    carts = {
        1: {"id": 1, "customer_id": 101, "items": [{"product_id": 201, "quantity": 2}], "total_price": 50.0},
        2: {"id": 2, "customer_id": 102, "items": [{"product_id": 202, "quantity": 1}], "total_price": 20.0},
    }
    
    return carts.get(cart_id, {})

# get-cart-items: 
# This tool will return a list of items in the cart. 
# The input is the cart ID, and the output is a list of items. 
# Each item should contain the following fields: ID, name, description, price, quantity, and product ID.
@mcp.tool()
def get_cart_items(cart_id: int) -> list[dict]:
    """Retrieve a list of items in a cart by its ID
    args:
        cart_id (int): The ID of the cart to retrieve items from.
    returns:
        list[dict]: A list of items in the cart, each represented as a dictionary with fields:
                    ID, name, description, price, quantity, and product ID.
    """
    # Sample data representing cart items
    cart_items = {
        1: [
            {"id": 1, "name": "Product A", "description": "Description A", "price": 25.0, "quantity": 2, "product_id": 201},
        ],
        2: [
            {"id": 2, "name": "Product B", "description": "Description B", "price": 20.0, "quantity": 1, "product_id": 202},
        ],
    }
    
    return cart_items.get(cart_id, [])

# add-to-cart: 
# This tool will add an item to the cart. 
# The input is the cart ID, product ID, and quantity. 
# The output is a success message. If the cart ID is not provided, the tool 
# should create a new cart and add the item to the new cart. The output should be 
# a success message and the cart ID.
@mcp.tool()
def add_to_cart(cart_id: int = None, product_id: int = None, quantity: int = 1) -> dict:
    """Add an item to the cart, creating a new cart if necessary
    args:
        cart_id (int, optional): The ID of the cart to add the item to. Defaults to None.
        product_id (int): The ID of the product to add to the cart.
        quantity (int, optional): The quantity of the product to add. Defaults to 1.
    returns:
        dict: A dictionary containing a success message and the cart ID.
    """
    if cart_id is None:
        # Simulate creating a new cart
        cart_id = 3  # In a real scenario, this would be generated by the database
    
    # Simulate adding the item to the cart
    # In a real scenario, this would involve updating the database
    
    return {"message": f"Added product {product_id} (quantity: {quantity}) to cart {cart_id}.", "cart_id": cart_id}

# products: 
# This tool will return a list of products. The optional input is a category, and the 
# output is a list of products. The product should contain the following fields: 
# ID, name, description, price, and category. The output should be in JSON format.
@mcp.tool()
def get_products(category: str = None) -> list[dict]:
    """Retrieve a list of products, optionally filtered by category
    args:
        category (str, optional): The category to filter products by. Defaults to None.
    returns:
        list[dict]: A list of products, each represented as a dictionary with fields:
                    ID, name, description, price, and category.
    """
    # Sample data representing products
    products = [
        {"id": 201, "name": "Product A", "description": "Description A", "price": 25.0, "category": "Electronics"},
        {"id": 202, "name": "Product B", "description": "Description B", "price": 20.0, "category": "Books"},
        {"id": 203, "name": "Product C", "description": "Description C", "price": 15.0, "category": "Electronics"},
    ]
    
    if category is not None:
        # Filter products by category
        products = [product for product in products if product["category"] == category]
    
    return products

# product: 
# This tool should return a specific product. The input is the product ID, and the output is a product. 
# The product should contain the following fields: name, description, price, category, and ID. 
# The output should be in JSON format.
@mcp.tool()
def get_product(product_id: int) -> dict:
    """Retrieve a specific product by its ID
    args:
        product_id (int): The ID of the product to retrieve.
    returns:
        dict: A dictionary representing the product with fields:
              ID, name, description, price, and category.
    """
    # Sample data representing products
    products = {
        201: {"id": 201, "name": "Product A", "description": "Description A", "price": 25.0, "category": "Electronics"},
        202: {"id": 202, "name": "Product B", "description": "Description B", "price": 20.0, "category": "Books"},
        203: {"id": 203, "name": "Product C", "description": "Description C", "price": 15.0, "category": "Electronics"},
    }
    
    return products.get(product_id, {})

# categories: 
# This tool will return a list of categories. The output should be in JSON format. 
# The categories should contain the following fields: ID, name, and description. 
# The output should be in JSON format.
@mcp.tool()
def get_categories() -> list[dict]:
    """Retrieve a list of product categories
    returns:
        list[dict]: A list of categories, each represented as a dictionary with fields:
                    ID, name, and description.
    """
    # Sample data representing categories
    categories = [
        {"id": 1, "name": "Electronics", "description": "Electronic gadgets and devices."},
        {"id": 2, "name": "Books", "description": "Various kinds of books and literature."},
    ]
    
    return categories

# get-customers: 
# This tool will return a list of customers. The output should be in JSON format. 
# It should contain the following fields: ID, name, and email.
@mcp.tool()
def get_customers() -> list[dict]:
    """Retrieve a list of customers
    returns:
        list[dict]: A list of customers, each represented as a dictionary with fields:
                    ID, name, and email.
    """
    # Sample data representing customers
    customers = [
        {"id": 101, "name": "Alice Smith", "email": "asmith@gmail.com"},
        {"id": 102, "name": "Bob Johnson", "email": "bjohnson@gmail.com"},
    ]
    return customers

# product_catalog: 
# This resource will return a list of products in the catalog. 
# The optional input is a category, and the output is a list of products. 
# Each product should contain the following fields: name, description, and category. 
# The idea is that the resource will return a list of products in the catalog, in case 
# potential customers want to see them.
@mcp.resource("product_catalog://{category}")
def get_product_catalog(category: str = None) -> list[dict]:
    """Retrieve a list of products in the catalog, optionally filtered by category
    args:
        category (str, optional): The category to filter products by. Defaults to None.
    returns:
        list[dict]: A list of products, each represented as a dictionary with fields:
                    name, description, and category.
    """
    # Sample data representing products
    products = [
        {"name": "Product A", "description": "Description A", "category": "Electronics"},
        {"name": "Product B", "description": "Description B", "category": "Books"},
        {"name": "Product C", "description": "Description C", "category": "Electronics"},
    ]
    
    if category is not None:
        # Filter products by category
        products = [product for product in products if product["category"] == category]
    
    return products


